### ISSUE TITLE
Target for Android v2.2+ is not accurate

### ISSUE THREAD

**Issue by ZionPi** [Tibolte/ElasticDownload#22]
Drawable added [`getAlpha`](http://developer.android.com/reference/android/graphics/drawable/Drawable.html) method in API level19.
add [`applyTheme`](http://developer.android.com/reference/android/graphics/drawable/Drawable.html#applyTheme%28android.content.res.Resources.Theme%29) in API 21,how can I implement those method in lower version,say min API 12 ?

**Comment by Tibolte** [comment]
I believe you are talking about applyTheme() and getAlpha() from the VectorCompat library. They are backported methods and have their own implementation
Have you tried running the example on a device that work under 12?

**Comment by ZionPi** [comment]
I donot run the example,only include source code to my example project,after comment those `override` annotations to remove errors(caused by high API level  demand).Finally, I can see the dialogue.But with rather crappy theme far from your illustration gifs.

**Comment by Tibolte** [comment]
Have you imported all the source code as a library or have it as a Gradle dependency?

**Comment by ZionPi** [comment]
My workspace is eclipse,do not have any knowledge of Gradle.

**Comment by Tibolte** [comment]
allright, I have dropped Eclipse a while ago :)

Also do you have ElasticDownload having appcompat-v7 and nineoldandroids as dependencies?

**Comment by ZionPi** [comment]
I have nineoldandroids but do not have  appcompat-v7.I'll give it a try,thanks!

**Comment by Tibolte** [comment]
@ZionPi any update on that?
