### ISSUE TITLE
Bug on 

### ISSUE THREAD

**Issue by Ashok-Varma** [Tibolte/ElasticDownload#24]
i followed your example.
i works fine. But if we come back to the activity. Its not showing download button by default

I mean we have two activities. we went from 1st to 2nd and in 2nd activity we have your view. First time when we open 2nd activity from 1st, it works fine. But Once we start some download (failed or downloaded) and then when i go back to 1st and come back again to second instead of showing download its showing 3rd image.

Solution:-
Just add method like elasticdownloader.showDownloadButton() which shows download button.

Please also try to add methods to change the colors of download button

First time i opened

![screenshot_2015-08-03-15-26-59](https://cloud.githubusercontent.com/assets/9069318/9035414/262dedc6-39f5-11e5-95b5-7883686ced51.png)

Fail or pass
![screenshot_2015-08-03-15-33-03](https://cloud.githubusercontent.com/assets/9069318/9035416/262ea798-39f5-11e5-8ef1-d573ed322ac2.png)

Went back to first activity an came back to 2nd i shows the image below instead of download button
![screenshot_2015-08-03-15-33-10](https://cloud.githubusercontent.com/assets/9069318/9035415/262df2e4-39f5-11e5-8a44-c3b75b9e75bf.png)

**Comment by Tibolte** [comment]
Good input, I'll try to improve what you pointed out.

**Comment by Ashok-Varma** [comment]
@Tibolte  thankyou verymuch.
Damn good library, and especially the support till 2.2 was great

**Comment by Ashok-Varma** [comment]
@Tibolte can you inform me once its fixed. I have nearly 50k users. So i can't implement it in my app until the bug is fixed

**Comment by Tibolte** [comment]
Sure you'll be notified here, I am doing it on my spare time, which is not easy to find these days ;) I hope to fix it by the end of the week.

**Comment by Tibolte** [comment]
I think what you observed is the view restoring its state, I didn't handle it. I'm currently working on a branch, I made some changes so we show the download button when restoring the view state. Can you just tell me what colors you want customizable on the view? That'll help me set-up a new release.

**Comment by Ashok-Varma** [comment]
@Tibolte 
1) Download Icon color 

public static Drawable getTintedDrawable(Drawable d, int color) {
        Drawable wrappedDrawable = DrawableCompat.wrap(d);
        DrawableCompat.setTint(wrappedDrawable, color);
        return wrappedDrawable;
}
You need latest support library to use that method

2) Color Surrounding the DownloadIcon,which is same as string color.

These are two main changes that need to be changed, If you wish you can also add for text color...etc

I am updating my app this weekend you can keep :- play.google.com/store/apps/details?id=com.ashokvarma.cocguidewiki
Thanks to you, You decreased the amount of work i have to do

**Comment by Ashok-Varma** [comment]
You need latest support library to use that method

**Comment by Tibolte** [comment]
Allright, these are good ideas :+1:  I'll see what I can do.

**Comment by Tibolte** [comment]
@Ashok-Varma sorry for the delay. I've been looking for solutions on how to dynamically change colors on path groups, this is harder than it looks. I'm wondering if that's really possible to do it. The only customizable color I can offer now is the background (green on your screenshots) behind the animated view. Let me know if those features can wait. I'd like to release the fix with restoring state.

**Comment by Ashok-Varma** [comment]
@Tibolte yeah you can release, the fix with restoring state, now.
Those features can wait.
And will this update solve #25 issue ??

**Comment by Tibolte** [comment]
Let me see if I can solve #25 today. I'll try to release something this evening. I'll probably open an issue regarding the colors separately.

**Comment by Ashok-Varma** [comment]
I will open issue regarding feature mark it as a feature.

**Comment by Ashok-Varma** [comment]
Issue opened @Tibolte

**Comment by Tibolte** [comment]
The fix for restoring view state is released under version 1.0.4, it will be available any time soon with Maven. Couldn't get time for #25.

**Comment by Tibolte** [comment]
1.0.4 is out, restoring state should be fixed then.
