### ISSUE TITLE
How to change the background color of this view?

### ISSUE THREAD

**Issue by vj-1023** [Tibolte/ElasticDownload#28]
@Tibolte 

<is.arontibo.library.ElasticDownloadView
        android:id="@+id/elastic_download_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="#FFFFFF"
        android:layout_below="@+id/logo_layout"
        android:layout_centerInParent="true" />

doesn't do anything !

**Comment by Tibolte** [comment]
Sorry for the late reply, you need to use android:backgroundColor instead of android:background

**Comment by ahmadalibaloch** [comment]
`android:backgroundColor` There is no such attribute!
